Pipfile
Pipfile.lock
generate_compose/odcs_fetcher.py
tests/test_odcs_fetcher.py

Adds a method to pull and store ODCS compose.

chore: fetch and store ODCS compose

---

tests/test_compose_generator.py

Test ComposeGenerator class using mock dependencies

test(RHTAPWATCH-672): add tests for compose_generator

---

generate_compose/odcs_compose_generator.py
generate_compose/odcs_configurations_generator.py
generate_compose/odcs_fetcher.py
generate_compose/odcs_requester.py
tests/test_odcs_compose_generator.py
tests/test_odcs_fetcher.py

Change the implementation of odcs-related code so it allows multiple requests to odcs to be called. This includes changing the input format from using container and content_sets yamls to using a yaml based on the the odcs python client architecture.

refactor(RHTAPWATCH-684): support multiple calls to odcs

---

tests/test_rpm_verifier.py
verify_rpms/rpm_verifier.py

add the ability to extract images from snapshot
add tests

chore(RHTAPWATCH-682): add the ability to extract images from snapshot

---

tests/test_rpm_verifier.py
verify_rpms/rpm_verifier.py

Except exceptions from runner
Add errors to the output
Add unit tests

chore(RHTAPWATCH-686): handle runner exceptions

---

generate_compose/compose_generator.py
generate_compose/odcs_configurations_generator.py
generate_compose/odcs_fetcher.py
generate_compose/odcs_requester.py
tests/test_odcs_fetcher.py
tests/test_odcs_requester.py

Implement ODCSRequestor, allowing requesting ODCS
for a compose file.

chore(RHTAPWATCH-634): request ODCS compose

---

generate_compose/compose_generator.py
generate_compose/odcs_compose_generator.py
generate_compose/odcs_configurations_generator.py
generate_compose/odcs_fetcher.py
generate_compose/odcs_requester.py
generate_compose/protocols.py
tests/test_compose_generator.py
tests/test_odcs_compose_generator.py
tests/test_odcs_requester.py

At first, the protocols were non-odcs oriented, which required over-complicating the implementation in order to keep it generic.
Instead, we now make the protocols targeting odcs directly and keep only the implementation generic rather than the dataclasses that are passed around.

refactor: make the protocols odcs-oriented

---

generate_compose/compose_generator.py
generate_compose/odcs_configurations_generator.py
generate_compose/odcs_requester.py
generate_compose/protocols.py
tests/test_compose_generator.py
tests/test_odcs_configurations_generator.py
tests/test_odcs_requester.py

Generate configurations to be used to request an ODCS compose,
using parameters from a yaml file.
Also fixed a few minor bugs, as the added functionality allowed testing
the process end to end for the first time.

chore(RHTAPWATCH-633): Generate ODCS configurations

---

generate_compose/odcs_requester.py
tests/test_odcs_requester.py

Previously, we only covered failures that caused exceptions. With this change, also detect composed that finish and indicate their failure inside the compose record.

fix(RHTAPWATCH-688): identify compose failures

---

Pipfile
Pipfile.lock
pyproject.toml

Adds the pylint-pytest pylint plugin to help
differentiate between code-relevant and test-relevant issues when running pylint on test files.
more info available on pypi: https://pypi.org/project/pylint-pytest/

chore: test pylint with pylint-pytest plugin

---

tests/test_rpm_verifier.py
verify_rpms/rpm_verifier.py

The code was expecting snapshot objects to be encapsulated inside a spec field, but this is not the case.

fix(RHTAPWATCH-694): snapshot should not have spec field

---

tests/test_rpm_verifier.py
verify_rpms/rpm_verifier.py

The e2e test for the verify-rpms script checked
only a scenario where it should not fail when unsigned RPMs
or errors exists.
Adds tests for multiple scenarios - where the script should
and should not fail when encountering unsigned RPMs or other errors.
This lead to a refactor which changed the failing responsability
from which fails the process from "generate_output" to the
main function.

chore(RHTAPWATCH-691): verify-rpms test to fail on unsigned RPMs

---

generate_compose/odcs_fetcher.py
tests/test_odcs_fetcher.py

yum/dnf will only take into consideration files with .repo suffix. This change adds the suffix to the generated files.

fix: add extensions to generated repofiles

---

generate_compose/odcs_compose_generator.py
tests/test_odcs_compose_generator.py

Currently, if the input YAML is missing, a generic error exception will tell the file is missing. This change raises a clearer exception.

chore(KONFLUX-887): show nicer output for missing compose input file

---

CONTRIBUTING.md
Pipfile
Pipfile.lock
generate_compose/odcs_compose_generator.py
generate_compose/odcs_ping.py
generate_compose/odcs_requester.py
generate_compose/odcs_session.py
tests/test_odcs_requester.py
tests/test_odcs_session.py

use OIDC for authentication with ODCS instead of kerberos. This will allow us to drop the need of maintaining the kerberos cache using additional cronjob.

chore(RHTAPWATCH-825): authenticate with oidc

---

.tekton/tools-push.yaml
tasks/update_private_repo.yaml

Automate update image references in `tekton-tools`
when changes are merged in `tools`
- Add `update_private_repo.yaml` task to update private repositories
- Add a task to the push pipeline to create a PR in `tekton-tools`
References for the update_private_repo.yaml:
- [authenticate as a github-app-installation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation)
- [Generate JWT using bash](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#example-using-bash-to-generate-a-jwt)

chore(RHTAPWATCH-717): update image references in tekton-tools

---

Dockerfile
tests/test_rpm_verifier.py
verify_rpms/rpm_verifier.py

Add support for image index.
An image reference can also be a reference to image index which contains several image manifests (for different archs for example)
- add support for image-url and image-digest
- add skopeo to dockerfile
- in case of image-index scan all images
- output all images

chore(RHTAPWATCH-1304): add support for image index

---

Dockerfile
tests/test_rpm_verifier.py
verify_rpms/rpm_verifier.py

Aggregate results from all images
- aggregate the results in case there is no error and create a final result
- result will be written to \results
- if an error occurred in one of the images, the result will be the error.
This PR relies on https://github.com/redhat-appstudio/tools/pull/236 and will be rebased once it will be merged

chore(RHTAPWATCH-1305): Aggregate results from all images

---

tests/test_rpm_verifier.py
verify_rpms/rpm_verifier.py

The old format string here would miss key ids from epel and other sources.

fix: rpm signature identification

---

Dockerfile

We need Helm cli installed on an image so we can use for releasing Helm charts. Let's piggyback on this image for now.

chore(KFLUXVNGD-193): add helm to dockerfile

---

.tekton/tools-pull-request.yaml
.tekton/tools-push.yaml

This actually mainly includes updating old quay references

chore: update tools after move to konflux-ci

---

Dockerfile

It is needed to help helm select the right auth from a dockerconfig json containing multiple auths.

chore(KFLUXVNGD-283): install jq

---

renovate.json

This should slow down the influx of dependency updates and batch them, which will in turn slow down the influx of changes to the build-definitions repo. Throttling our rebuilds.

Establish a renovate schedule

---

renovate.json

Groups Python dev tools (black, mypy, pylint, pytest) into single PRs, groups Tekton bundles and container image updates, adds GitHub Actions management with smart grouping, and adds framework for future automerge

feat: enhance renovate config with dependency grouping and automerge framework
